compatibility_date = "2022-07-14"
name = "miniflare-debug-objects"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[build.upload]
format = "modules"

[durable_objects]
bindings = [{ name = "LIST", class_name = "List" }]

[[migrations]]
tag = "v1"
new_classes = ["List"]
